language: c
sudo: false
cache:
  directories:
    - ~/container
before_install:
 # As a special case for this project, copy all the shell scripts into
 # the container directory, so that we can use them directly.
 - mkdir -p ~/container/_scripts
 - rsync -r -u travis/* ~/container/_scripts/
 - export __POLYSQUARE_CI_SCRIPTS_BOOTSTRAP="~/container/_scripts/bootstrap.sh"
 - eval "$(bash ~/container/_scripts/bootstrap.sh -d ~/container -s setup/shell/setup.sh)"
 # For now
 - source ~/container/_scripts/haskell-util.sh
 - eval "$(polysquare_task \"Installing pandoc\" \
           polysquare_run_if_unavailable pandoc \
           polysquare_cabal_install_binary pandoc)"
script:
 - polysquare_run_check_script check/shell/check.sh -d travis -d tests
 - polysquare_run_deploy_script deploy/shell/deploy.sh -d ~/container
